# Generated by Django 5.1.6 on 2025-03-04 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0002_rename_customer_id_booking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
