# Generated by Django 5.1.6 on 2025-03-05 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0008_booking_end_time_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer')], default='Transfer', max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
